### ISSUE TITLE
crash running against 1.5 dev build

### ISSUE THREAD

**Issue by erichexter** [PocketDock/PocketDockConsole#15]
Here is the crash dump running against pm 1,5 is this a known issue?  Is there a specific build that PDC works against?

[12:36:44] [Server thread/INFO]: Loading pocketmine.yml...
[12:36:44] [Server thread/INFO]: Loading server properties...
[12:36:44] [Server thread/INFO]: Selected English (eng) as the base language
[12:36:44] [Server thread/INFO]: Starting Minecraft: PE server version v0.11.0 alpha
[12:36:44] [Server thread/NOTICE]: The memory-limit setting has been deprecated.
[12:36:44] [Server thread/NOTICE]: There are new memory settings on pocketmine.yml to tune memory and events.
[12:36:44] [Server thread/NOTICE]: You can also reduce the amount of threads and chunks loaded control the memory usage.
[12:36:44] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[12:36:45] [Server thread/INFO]: This server is running PocketMine-MP version 1.5dev-1240 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)
[12:36:45] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[12:36:46] [Server thread/INFO]: Loading ManyWorlds v2.0.0
[12:36:46] [Server thread/INFO]: Loading PocketDockConsole v0.0.12
[12:36:46] [Server thread/INFO]: [PDC] Loaded
[12:36:47] [Server thread/INFO]: Preparing level "Creative"
[12:36:47] [Server thread/INFO]: Enabling ManyWorlds v2.0.0
[12:36:47] [Server thread/INFO]: Enabling PocketDockConsole v0.0.12
[12:36:47] [Server thread/INFO]: [PDC] Enabled
[12:36:47] [Server thread/INFO]: [PDC] Started SocksServer on 0.0.0.0:9090
[12:36:48] [Server thread/INFO]: Starting GS4 status listener
[12:36:48] [Server thread/INFO]: Setting query port to 19132
[12:36:48] [Server thread/INFO]: Query running on 0.0.0.0:19132
[12:36:48] [Server thread/INFO]: Default game type: Creative Mode
[12:36:48] [Server thread/INFO]: Done (4.537s)! For help, type "help" or "?"

Fatal error: Call to undefined method pocketmine\Server::getMemoryUsage() in phar://C:/Users//Downloads/PocketMine-MP/plugins/PocketDockConsole_v0.0.12.phar/src/PocketDockConsole/RunCommand.php on line 171

Call Stack:
    0.0586     407680   1. {main}() C:\Users\\Downloads\PocketMine-MP\PocketMine-MP.phar:0
    0.0673     402648   2. require('phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\hexteradmin\Downloads\PocketMine-MP\PocketMine-MP.phar:1
    0.4597     541448   3. pocketmine\Server->__construct() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
    4.5345   13242624   4. pocketmine\Server->start() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1783
    4.6070   13339528   5. pocketmine\Server->tickProcessor() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2178
    5.5586   13344632   6. pocketmine\Server->tick() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2300
    5.5587   13344696   7. pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2492
    5.5588   13344400   8. pocketmine\scheduler\TaskHandler->run() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/ServerScheduler.php:247
    5.5588   13344400   9. PocketDockConsole\RunCommand->onRun() phar://C:/Users//Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/TaskHandler.php:150
    5.5589   13344728  10. PocketDockConsole\RunCommand->updateInfo() phar://C:/Users//Downloads/PocketMine-MP/plugins/PocketDockConsole_v0.0.12.phar/src/PocketDockConsole/RunCommand.php:43

[12:36:49] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[12:36:49] [Server thread/EMERGENCY]: Please upload the "C:\Users\\Downloads\PocketMine-MP\CrashDump_Sat_Jun_13-12.36.49-UTC_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[12:36:51] [Server thread/INFO]: Disabling ManyWorlds v2.0.0
[12:36:51] [Server thread/INFO]: Disabling PocketDockConsole v0.0.12
[12:36:51] [Server thread/INFO]: [PDC] Disabled
[12:36:51] [Server thread/INFO]: Unloading level "Creative"

**Comment by Humerus** [comment]
Interesting, I thought I pushed an update for this before. I'll push an update and it'll be available on the forums in a few minutes.

**Comment by erichexter** [comment]
Cool, thanks for the super fast response. So this will be v 0.0.13 ?

**Comment by Humerus** [comment]
Yep, building as we speak :)

**Comment by Humerus** [comment]
You can grab the new release from here: https://github.com/PocketDock/PocketDockConsole/releases/tag/v0.0.13

**Comment by erichexter** [comment]
Crazy,, so this is what I still get.... using v0.0.13

Fatal error: Call to undefined method pocketmine\utils\Utils::getRealMemoryUsage() in phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/plugins/PocketDockConsole_v0.0.13.phar/src/PocketDockConsole/RunCommand.php on line 178

Call Stack:
    0.0942     407680   1. {main}() C:\Users\hexteradmin\Downloads\PocketMine-MP\PocketMine-MP.phar:0
    0.0970     402648   2. require('phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\hexteradmin\Downloads\PocketMine-MP\PocketMine-MP.phar:1
    0.3905     541448   3. pocketmine\Server->__construct() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
    8.1320   14027992   4. pocketmine\Server->start() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1783
    8.2021   14125128   5. pocketmine\Server->tickProcessor() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2178
    9.1668   14129744   6. pocketmine\Server->tick() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2300
    9.1669   14129808   7. pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2492
    9.1670   14129512   8. pocketmine\scheduler\TaskHandler->run() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/ServerScheduler.php:247
    9.1670   14129512   9. PocketDockConsole\RunCommand->onRun() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/TaskHandler.php:150
    9.1671   14129824  10. PocketDockConsole\RunCommand->updateInfo() phar://C:/Users/hexteradmin/Downloads/PocketMine-MP/plugins/PocketDockConsole_v0.0.13.phar/src/PocketDockConsole/RunCommand.php:45

[19:45:08] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[19:45:08] [Server thread/EMERGENCY]: Please upload the "C:\Users\hexteradmin\Downloads\PocketMine-MP\CrashDump_Sat_Jun_13-19.45.08-UTC_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Humerus** [comment]
Are you running the latest version of PocketMine?

**Comment by erichexter** [comment]
Yes the latest alpha. I could not find older releases of 1.5. What version
are you running ?

On Saturday, June 13, 2015, Humerus <notifications@github.com> wrote:

> Are you running the latest version of PocketMine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketDock/PocketDockConsole/issues/15#issuecomment-111754570>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by Humerus** [comment]
I'm running the latest development build, it's 1.5dev-1244

**Comment by erichexter** [comment]
That's what I am running, not sure what php  version is installed with the
default installer. And I'm running on a windows server,

On Saturday, June 13, 2015, Humerus <notifications@github.com> wrote:

> I'm running the latest development build, it's 1.5dev-1244
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketDock/PocketDockConsole/issues/15#issuecomment-111758460>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by Humerus** [comment]
Can you upload the crash dump file so i can follow the complete trace?

**Comment by erichexter** [comment]
Yes absolutely. I'm out for the night but I will send it out tomorrow or
late tonight .

On Saturday, June 13, 2015, Humerus <notifications@github.com> wrote:

> Can you upload the crash dump file so i can follow the complete trace?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketDock/PocketDockConsole/issues/15#issuecomment-111759427>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by erichexter** [comment]
Here is the crashdump.  https://gist.github.com/erichexter/f734e7b0544310379b49

**Comment by shoghicp** [comment]
@humerusj getRealMemoryUsage() will only work on Linux for now, use the old getMemoryUsage() as that shows the usage with stack, heap and loaded libraries

**Comment by Humerus** [comment]
@shoghicp ahh, didn't see that clarification anywhere. I'll fix that in a bit.

**Comment by erichexter** [comment]
@shoghicp I was running build 1240, it looks like this works for build 1244.  Sorry about jumping to conclusions on this one.

**Comment by erichexter** [comment]
I was able to download 1244 from the PM jenkins server and now the PDC is loaded.

**Comment by Humerus** [comment]
Does it work as described?

**Comment by erichexter** [comment]
Yes! I  have the console up and running, I have not tried a ton of commands yet, but the console loaded and is streaming to my browser.
